name:                           Docker Image Tag and Latest Release

on:
  push:
    tags:
      - v*

jobs:
  deploy-docker:
    name:                       Build Release
    runs-on:                    ubuntu-latest
    steps:
      - name:                   Checkout sources
        uses:                   actions/checkout@master
      - name:                   Set env
        run:                    echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name:                   Install toolchain
        uses:                   actions-rs/toolchain@v1
        with:
          toolchain:            stable
          profile:              minimal
          override:             true
      - name:                   Deploy to docker hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: openethereum/openethereum
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: scripts/docker/alpine/Dockerfile
          tags: "latest,${{ env.RELEASE_VERSION }}"
